### ISSUE TITLE
Enclaves crashes Nginx every 10mn

### ISSUE THREAD

**Issue by urluba** [aws/aws-nitro-enclaves-acm#37]
Hi,

I've setup a customized Amazon Linux 2 with Enclaves and a Nginx App Protect (NAP):

```
aws-nitro-enclaves-cli-1.0.11-0.amzn2.x86_64
aws-nitro-enclaves-acm-1.0.1-2.amzn2.x86_64
nginx-plus-module-ndk-24+0.3.1-1.el7.ngx.x86_64
nginx-plus-module-lua-24+0.10.19-1.el7.ngx.x86_64
nginx-plus-24-2.el7.ngx.x86_64
nginx-plus-module-appprotect-24+3.583.0-1.el7.ngx.x86_64
app-protect-compiler-7.7.7-1.el7.ngx.x86_64
app-protect-threat-campaigns-2021.06.29-1.el7.ngx.x86_64
app-protect-engine-7.7.7-1.el7.ngx.el7.centos.x86_64
app-protect-attack-signatures-2021.07.01-1.el7.ngx.x86_64
app-protect-24+3.583.0-1.el7.ngx.x86_64
app-protect-plugin-3.583.0-1.el7.ngx.x86_64
```

Every 10mn, my nginx died of a sudden death. It appears that it was because of Nitro which tries to reload Nginx [every 10mn](https://github.com/aws/aws-nitro-enclaves-acm/blob/bcc62899f3a081c0555443e4ff4f323dddb8d30e/src/vtok_agent/src/agent/mod.rs#L161)...
Problem is, with the modules loaded in my Nginx setup, it needs more than 1s to reload and was killed too soon by the SIGQUIT.

I've solved my issue by editing `acm.yaml` and add a "options" section:

```yaml
options:
  nginx_reload_wait_ms: 20000
```

Would it be possible to add an option to disable this behavior and review documentation to give a clear explanation of this behavior?

Thanks

**Comment by dblanzeanu** [comment]
Hi @urluba,

After the 10min mark when reloading the nginx, p11ne-agent sends the following signals to nginx: `SIGUSR2`, `SIGWINCH`, `wait(wait_ms)` and `SIGQUIT`. This sequence should terminate the nginx process gracefully, however, in your case it takes longer than the preset `wait_ms` time to upgrade executable(`SIGUSR2`)/shutdown worker processes(`SIGWINCH`) of nginx.

As you may have noticed, we only support Nginx in the ACM context and this specific scenario happens for NAP.

Your solution to add the option which modifies the `wait_ms` solves the issue you are experiencing, unfortunately on the current roadmap we do not have the change to add the option to disable this behavior, but we gladly accept and review PRs. We will open a feature request when such time will come.

**Comment by alcioa** [comment]
Hi @urluba does the workaround work for you or are you still encountering availability issues?

**Comment by urluba** [comment]
HI @alcioa ,

After setting `nginx_reload_wait_ms` option to a high value, I've not ran into this issue.

**Comment by alcioa** [comment]
Thanks. So to summarize - an NGINX reload takes place so that when the `pkcs#11` token update happens, NGINX shall correctly start new PKCS#11 sessions so that it accesses the token provisioned database.
