### ISSUE TITLE
Creating instance from "AWS Certificate Manager for Nitro Enclaves AMI" with Enclave enabled through console is not running nitro services 

### ISSUE THREAD

**Issue by vasav03** [aws/aws-nitro-enclaves-acm#38]
Following the [Blog](https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave-refapp.html#acm-ami)

Created an instance through console "AWS Certificate Manager for Nitro Enclaves AMI" with Encalve Enabled=true
tried to restart nitro acm services but failed with error " Failed to allocate CPUs for Enclaves"

But creating an instance through CLI from the same AMI and enclave enable=true option works fine.

**Comment by axlprv** [comment]
Hi @vasav03,

Thank you for reporting this. I managed to reproduce the issue and I am currently investigating it.

**Comment by andraprs** [comment]
This issue should be fixed. Let us know if additional help needed. Thank you.
