### ISSUE TITLE
Loop in p11ne-agent trying to reach IAM Endpoint

### ISSUE THREAD

**Issue by urluba** [aws/aws-nitro-enclaves-acm#55]
Hi,

I've deployed an AWS-Nitro-Enclaves in a VPC with no Internet access: a proxy has to be set for that. To declare the proxy, I use the following code and everything works great (well I've also multiple VPCEs to help 😄 ):

```shell
cat <<EOF >/etc/systemd/system/nitro-enclaves-acm.service.d/proxy.conf
[Service]
Environment=https_proxy=http://${ProxyFqdn}:8080/
Environment=no_proxy=.s3.eu-west-1.amazonaws.com
EOF
```

I've noticed that if I remove the proxy configuration - and still have no Internet access - aws-nitro-enclaves seems to enter an infinite loop trying to reach the IAM endpoint. But if I set a wrong proxy URL, it switches to IMDS and everything works just fine:

```
Feb 03 13:18:03 i-123456 systemd[1]: Starting Nitro Enclaves ACM Agent...
Feb 03 13:18:03 i-123456 systemd[1]: Started Nitro Enclaves ACM Agent.
Feb 03 13:18:04 i-123456 p11ne-agent[6805]: |INFO  | Setting up p11-kit config
Feb 03 13:18:04 i-123456 p11ne-agent[6805]: |INFO  | Restarting vsock proxy
Feb 03 13:18:14 i-123456 p11ne-agent[6805]: |WARN  | Cannot fetch IAM role arn using the AWS CLI iam get-role command. Falling back to using IMDS.
Feb 03 13:18:14 i-123456 p11ne-agent[6805]: |WARN  | For IAM roles with paths included, please add the IAM policy permission for iam:GetRole as per documentation -
 https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave-refapp.html.
Feb 03 13:18:15 i-123456 p11ne-agent[6805]: |INFO  | Syncing token nginx-acm-internal
Feb 03 13:18:20 i-123456 p11ne-agent[6805]: |WARN  | Cannot fetch IAM role arn using the AWS CLI iam get-role command. Falling back to using IMDS.
Feb 03 13:18:20 i-123456 p11ne-agent[6805]: |WARN  | For IAM roles with paths included, please add the IAM policy permission for iam:GetRole as per documentation -
 https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave-refapp.html.
Feb 03 13:18:21 i-123456 p11ne-agent[6805]: |INFO  | Reloading NGINX config
```

Do you confirm this behavior ? Would it be possible to configure IMDS by default ?

**Comment by urluba** [comment]
Hello @alcioa ,

I am not block as settings a fake proxy URL is a good enough workaround 😃 

We can close this issue if it is related to `AWS cli`

**Comment by alcioa** [comment]
@urluba Hi, I cannot do your setup, but I've emulated your failure with a bogus `aws cli` endpoint and it loops 3 times. 
The idea is that I cannot get an infinite loop and there is a direct fallback to IMDSv2. 

```
Feb 23 17:46:50 p11ne-agent[22553]: |INFO  | Setting up p11-kit config
Feb 23 17:46:50 p11ne-agent[22553]: |INFO  | Restarting vsock proxy
Feb 23 17:46:50 p11ne-agent[22553]: |WARN  | Cannot fetch IAM role arn using the AWS CLI iam get-role command. Falling back to using IMDS.
Feb 23 17:46:50 p11ne-agent[22553]: |WARN  | For IAM roles with paths included, please add the IAM policy permission for iam:GetRole as per documentation - https://docs.aws.amazon.com/
Feb 23 17:46:50 p11ne-agent[22553]: |INFO  | Syncing token nginx-acm-token
Feb 23 17:46:51 p11ne-agent[22553]: |WARN  | Cannot fetch IAM role arn using the AWS CLI iam get-role command. Falling back to using IMDS.
Feb 23 17:46:51 p11ne-agent[22553]: |WARN  | For IAM roles with paths included, please add the IAM policy permission for iam:GetRole as per documentation - https://docs.aws.amazon.com/
Feb 23 17:46:52 p11ne-agent[22553]: |INFO  | Reloading NGINX config
```
The two WARNs here is that when the service starts it always does a first-time sync for the token for checking the ACM certs.

**Comment by alcioa** [comment]
AWS CLI [precedance order](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence) fallbacks to IMDS eventually so some users might find this useful. Since you have a working solution we'll keep the current behavior.

**Comment by jplock** [comment]
@alcioa is the proxy required? I'm seeing a similar behavior but the code is not falling back to IMDSv2 very quickly which is causing my EC2 instances to recycle themselves in their ASG.

I'm trying to use ACM from within a VPC without a NATGW (but using various VPCEs)
