### ISSUE TITLE
Max value for sync interval ?

### ISSUE THREAD

**Issue by urluba** [aws/aws-nitro-enclaves-acm#93]
Hello,

I am using a commercial module with Nginx. Latest version of this module does not like at all the SIGUSR2 sent after the token sync and crashes.
Until the editor solves its issue, what would be the consequences if I configure the sync only once per day ? From my understanding and tests, the only drawback is that if I renew a certificate in ACM, it won't be retrieved. 

Bonus question, why this choice of SIGUSR2+SIGWINCH...  and not just use a SIGHUP?
 
Anyway, thanks for your work!

**Comment by shtaked** [comment]
Should be a SIGHUP after https://github.com/aws/aws-nitro-enclaves-acm/pull/95.
The max sync interval possible at this moment would be 48 hours, otherwise enclave would initiate expiration of the token

**Comment by urluba** [comment]
Thanks!
